---
title: About me
---

<h1 style="text-align: center; color:#8c7edc;">About Me</h1>


## Currently, I am a...

📊📈 **Data analyst** at [Trying Together](https://tryingtogether.org/), a non-profit organization supporting the work of early childcare and education.

💻📚 **PhD candidate** in <font color="#54bf8d">**Cognitive Psychology**</font> at the University of Pittsburgh working with [Melissa Libertus](https://www.lrdc.pitt.edu/people/researcher-detail.cshtml?id=530). My research focuses on:

-   Links between children's **early math** experiences in the **home learning environment (HLE)** and the development of their math skills.
-   Exploring **new methods** (i.e., behavioral coding and statistical modeling) for the **measurement** of the HLE, particularly caregiver-child **interactions**.

🧵🧩 Hobbyist currently focused on <b>[pie art](https://s-duong.github.io/art.html)</b> 🥧

## Prior to graduate school, I...

-   Managed the Lab for Early Social Cognition at the University of Maryland, College Park, under Jonathan Beier.
-   Conducted research at the [Social Cognitive Development Lab](http://www.socialcogdev.com/) directed by Yarrow Dunham at Yale University and under the mentorship of Richard Ahl.
-   Conducted research in the Math Department at the University of New Haven with [Yasanthi Kottegoda](https://www.newhaven.edu/faculty-staff-profiles/yasanthi-kottegoda.php) and [Ramesh Sharma](https://www.newhaven.edu/faculty-staff-profiles/ramesh-sharma.php).
-   See more of my experiences [here](https://s-duong.github.io/experience.html)!

