---
title: "Hello!"
---
<div class="column-left">

```{r, eval=FALSE}
# NOT BEING EVALUATED RIGHT NOW!!!!
# would like this to be static and placed somewhere on the page while the margins of this page are narrower...
# full directory: ~/Users/shirleyduong/Desktop/s-duong.github.io/
htmltools::img(src = knitr::image_uri(file.path("headshot_dec22.png")), # file
               alt = "headshot", 
               # max-width and height allow for responsive resizing
               #style = "float: right; max-width: 100%; height: auto" # css
               #style = "position:absolute; top:0; right:0; padding:10px;" # css
               style = "position:absolute; padding:10px;" # css
               )
```


## Connect

<!-- Would love for these to be icons and text! -->

[Email](mailto:shirleyduong5@gmail.com) \| [LinkedIn](https://www.linkedin.com/in/duongshirley/) \| [Github](https://github.com/s-duong) \| [ResearchGate](https://www.researchgate.net/profile/Shirley-Duong)

## I am a...

-   📊📈 **Data analyst** at [Trying Together](https://tryingtogether.org/), a non-profit organization supporting the work of early childcare and education.
-   💻📚 **PhD candidate** in Cognitive Psychology at the University of Pittsburgh working with [Melissa Libertus](https://www.lrdc.pitt.edu/people/researcher-detail.cshtml?id=530). My research focuses on:
    -   Links between children's **early math** experiences in the **home learning environment (HLE)** and the development of their math skills.
    -   Applying **new methods** (i.e., behavioral coding and statistical modeling) to measuring the HLE, particularly **interactions** between children and their caregivers.
-   🥧🖼 [Pie artist](https://s-duong.github.io/art.html)! :)

## Prior to graduate school, I...

-   Managed the Lab for Early Social Cognition at the University of Maryland, College Park, under Jonathan Beier.
-   Conducted research at the [Social Cognitive Development Lab](http://www.socialcogdev.com/) directed by Yarrow Dunham at Yale University and under the mentorship of Richard Ahl.
-   Conducted research in the Math Department at the University of New Haven with [Yasanthi Kottegoda](https://www.newhaven.edu/faculty-staff-profiles/yasanthi-kottegoda.php) and [Ramesh Sharma](https://www.newhaven.edu/faculty-staff-profiles/ramesh-sharma.php).
-   See more of my experiences [here](https://s-duong.github.io/experience.html)!


</div>
