---
title: Select works
output:  
  html_document:  
    self_contained: no  
    theme: flatly
    toc: false
---

<!-- IDEAS? Include some visual of a research timeline here (for how academic research has evolved) -->
<!-- Definitely need to add VISUALS like a screenshot of the posters and stuff... maybe put these in boxes? Need to figure out how to make columns... -->

```{r, echo=FALSE}
aniview::use_aniview() # animate presence of content
```

<!-- for accessing the link icons --> 
<script src="https://kit.fontawesome.com/455169677b.js" crossorigin="anonymous"></script> 


::: {.aniview data-av-animation="fadeInUp"}

* [Profiles of home learning environments](#profiles-of-home-learning-environments)
* [Dynamic structures of social interactions](#dynamic-structures-of-social-interactions)
* [Exploration, uncertainty, and numerical judgements](#exploration-uncertainty-and-numerical-judgements)
* [Hot dasher summer](#hot-dasher-summer)
* [High cognitive demand questions](#high-cognitive-demand-questions)


<br>


<center>
Leading these projects have given me opportunities to engage deeply in:

<h5>**Data collection** | **Data cleaning** | **Exploratory data analysis** | **Visualization** | **Machine learning** | **Scientific communication**</h5>
</center>

<br>
<center>...</center>
<br>

Feel free to view a full list of projects on my <a href=publications.html>publications</a> page and/or <a href="mailto:shirleyduong5@gmail.com">ask me</a> about my work as <font color="#8c7edc">**data analyst**</font>!


<br>


# Profiles of home learning environments 

A **cluster analysis** of families' **early math** practices, including math-related conversations and activities. This is my <font color="#8c7edc">**dissertation**</font> project, in which I am also **classifying** families into clusters based on various cognitive, affective, and socioeconomic factors and using these derived clusters to **predict children's academic skills**. 

This project <font color="#8c7edc">extends my previous work</font>, a **cluster analysis** of dyadic interactions using various **language input** measures. [<a href="Duong_CogTalk_Nov21_NumberClusters_Slides.pdf">Slides for <i>Pitt Cognitive Talk Series</i></a>] [<a href="DuongEtAl-2022_CDS.pdf">Poster for <i>Cognitive Development Society Meeting</i></a>]

<span class="badge bg-primary">R</span> <span class="badge bg-primary">Ruby</span> <span class="badge bg-success"><i>k</i>-means cluster analysis</span> <span class="badge bg-success">hierarchical cluster analysis</span> <span class="badge bg-success">multinomial logistic regression</span> <span class="badge bg-success">inter-rater reliability</span> <span class="badge bg-success">descriptive analysis</span> <span class="badge bg-success">transcription coding</span> <span class="badge bg-secondary">Qualtrics</span> <span class="badge bg-secondary">Datavyu</span> 

<br>


# Dynamic structures of social interactions

A visual and quantitative analysis of **dyadic interactions** between caregivers and children using **cross-recurrence quantification analysis (CRQA)**. Specifically, this project extracts additional measures of interactions beyond frequencies of input (e.g., words, utterances), such as the presence and duration of **reciprocal** exchanges. This work is a <font color="#8c7edc"><b>collaboration</b></font> with <a href="https://researchdirectory.uc.edu/p/davtj">Tehran Davis</a> at the University of Cinncinati.  

[<a href="https://github.com/s-duong/crqa-number-talk">Analysis code + Tutorial</a>] [<a href="Duong_CogTalk_Nov22_CRQA_Slides.pdf">Slides for <i>Pitt Cognitive Talk Series</i></a>] [<a href="">Journal article (under review)</a>]

There are several parts:

- Chronological **literature review** on the application of CRQA in early language research.
- **Case study** and **tutorial** of CRQA on existing transcription data of dyadic conversations about numbers and math.
- **Qualitative analysis** comparing frequency and CRQA measures of conversations and a **quantitative analysis** of the relations between input measures and children's academic skills. 

<span class="badge bg-primary">R</span> <span class="badge bg-primary">Ruby</span> <span class="badge bg-success">event/time series analysis</span> <span class="badge bg-success">recurrence analysis</span> <span class="badge bg-success">inter-rater reliability</span> <span class="badge bg-success">descriptive analysis</span> <span class="badge bg-success">transcription coding</span> <span class="badge bg-secondary">Qualtrics</span> <span class="badge bg-secondary">Datavyu</span> 


<br>


# Exploration, uncertainty, and numerical judgements

An **eye-tracking** study of **exploratory behavior**, i.e., eye switching frequency, during **numerical comparisons** and math skills in **children** [<a href="https://github.com/s-duong/exploration-eyetracking-ans/blob/main/Final_Project_Duong.ipynb">Jupyter Notebook</a>] and **adults** [<a href="Duong_Fall2020_CMU_BrainBag.pdf">Slides for <i>CMU Brain Bag</i></a>] [<a href="DuongLibertus-2020_JDM.pdf">Poster for <i>Judgement and Decision Making Conference</i></a>]

<span class="badge bg-primary">R</span> <span class="badge bg-primary">Python</span> <span class="badge bg-primary">MATLAB</span> <span class="badge bg-success">mixed effects logistic regression</span> <span class="badge bg-success">exploration simulations</span>


<br>


# Hot dasher summer

A <font color="#8c7edc">**personal**</font> project to **track**, **visualize**, and **analyze** data on my ongoing <font color="red">**DoorDash**</font> side gig.

<span class="badge bg-primary">R</span> <span class="badge bg-primary">SQL</span> <span class="badge bg-secondary">Tableau/Google Looker Studio/Shiny</span> 

<br>



# High cognitive demand questions

A multi-study project with 2 aims: 

- Explore **links** between children's exposure to caregivers' high (vs. low-) cognitive demand (CD) **questions** in the home learning environment and children's **early academic skills**. [<a href="">Analysis code</a>] [<a href="DuongEtAl-2021_JECP.pdf">Journal article in <i>Journal of Experimental Child Psychology</i></a>] 
- Investigate caregiver and child **factors** that **predict high-CD questioning**. [<a href="">Analysis code</a>] [<a href="">Journal article (under review)</a>]

<span class="badge bg-primary">R</span> <span class="badge bg-primary">Ruby</span> <span class="badge bg-primary">Stata</span> <span class="badge bg-success">linear regression</span> <span class="badge bg-success">mixed effects logistic regression</span> <span class="badge bg-success">inter-rater reliability</span> <span class="badge bg-success">power analysis</span> <span class="badge bg-success">transcription coding</span> <span class="badge bg-secondary">Qualtrics</span> <span class="badge bg-secondary">Datavyu</span> 


<br>

::: 
